In [31]:
# TAREA 5, Física Computacional.
# Fernando Maximiliano López Villegas, 316289201

In [32]:
# 1. Descomposición de LU.

In [33]:
from pylab import*

In [34]:
# a) Escriba un programa que calcule la descomposición de LU a partir del hecho en clase.


#Bueno, yo no asistí a esas clases pero aquí mi programa que es solo una copia en mis palabras del Newman.
A = array([[0,1,4,1],
           [0,4,-1,-1],
           [1,0,1,5],
           [2,-2,0,3]],float)
v = array([-4,3,9,7],float)
N = len(v)
#Gauss Elimination
for m in range(N):
    div = A[m,m]
#Partial Pivoting
    if div == 0:
        for w in range(m+1,N):
            if A[w,m] != 0:
                #temp = empty(N,float)
#Swapping rows                
                tempA = A[m,:].copy()
                A[m,:] = A[w,:]
                A[w,:] = tempA
#Swapping v's 
                tempv = v[m].copy()
                v[m] = v[w]
                v[w] = tempv
#al parecer si no usamos el .copy(), es una referencia y no una variable inmutable
#me tardé un rato en darme cuenta, pensé que estaba identando mal la cosa xD.
#En java no pasa eso, pero bueno, y algo muy asqueroso, que no usare porque no me acostumbro es:
#A[[m, w], :] = A[[w, m], :]
#lo vemos y hace sentido, pero amigo, no se me habia ocurrido manipular asi los rows.
                break
            else:
                continue
    div = A[m,m]
    A[m,:] /= div 
    v[m] /= div
    for i in range(m+1,N):
        mult = A[i,m]
        A[i,:] -= mult*A[m,:] 
        v[i] -= mult*v[m] 
#Backsubstitution
x = empty(N,float)
for m in range(N-1,-1,-1):
    x[m] = v[m]
    for i in range(m+1,N):
        x[m] -= A[m,i]*x[i]
print(x)



[ 1.56521739  0.79130435 -1.65217391  1.8173913 ]


In [35]:
#Se suponia que iba a poner mis desarrollos en la notebook, pero mejor voy a adjuntar un PDF, se me hace muy pesado
#a la vista tener código y 300 lineas de LateX solo porque si.


A = array([[2,1,4,1],
           [3,4,-1,-1],
           [1,-4,1,5],
           [2,-2,1,3]],float)
O  = A.copy() #Debemos mantener una referencia a la matriz A original pues al final del programa no es la misma.

v = array([-4,3,9,7],float)
vcopy = v.copy() #lo mismo que A

N = len(v)
######################################################
#Creación del hogar de las matrices L_{i} y L_{i}^{-1}
U = []
L = []
for i in range(N):
        L.append(np.zeros((N,N),float))
        U.append(np.zeros((N,N),float))
######################################################        
#Pivoting
#Hacemos el Pivoting antes porque como ya he dicho la amtriz A debe ser manipulable antes de comenzar 
#la descomposición LU
for m in range(N):
    div = A[m,m]
    if div == 0:
        for w in range(m+1,N):
            if A[w,m] != 0:            
                tempA = A[m,:].copy()
                A[m,:] = A[w,:]
                A[w,:] = tempA
                tempv = v[m].copy()
                v[m] = v[w]
                v[w] = tempv
                break
            else:
                continue
##################################################
#Gauss Elimination
for m in range(N):   
    ######################################
    #Creación de las matrices L_{i}, U_{i}
    W = L[m] 
    Q = U[m]
    z = 1/A[m,m].copy()
    #diagonal
    for p in range(N):
         if p == m:
             W[p,p] = z
             Q[p,p]  = A[m,m].copy()
         else:
             W[p,p] = A[m,m].copy()*z
             Q[p,p] = 1
    #renglón
    for p in range(m+1,N):
        W[p,m] = -A[p,m].copy()*z
        Q[p,m] = A[p,m].copy()
    ######################################
    div = A[m,m]
    A[m,:] /= div 
    v[m] /= div
    for i in range(m+1,N):
        mult = A[i,m]
        A[i,:] -= mult*A[m,:] 
        v[i] -= mult*v[m] 
######################################################
# Aquí ahora debemos armar la matriz L, y U, que si bien podriamos habernos 
#ahorrado las molestias, al momento de comentar me doy cuenta de que hice un revoltijo con la notación, en el github tengo 
#toda la historia de este código si quieren ver cuantas veces fue abortado.
# #Abuso de notación

import numpy as np
Normales = L # Las que no están invertidas pues
NormalesMult = Normales[-1]
for i in range(len(Normales)-2, -1, -1):
    NormalesMult = np.dot(NormalesMult, Normales[i])
Inversas  = U # Aca le falta la A, pero se entiende
InversasMult = Inversas[0]
for i in range(1, len(U)):
    InversasMult = np.dot(InversasMult, Inversas[i])
######################################################
#Se que me van a decir que esto puede causar muchos errores, pero si vieran como salen estas matrices, me darian la razón
#les voy a truncar los digitos hasta 5.

MatrizL = InversasMult
MatrizU = np.dot(NormalesMult,O) #listo, por eso ocupabamos guardar la A en O
#siendo honestos, creo que la unica que deberia ser truncada es la U, la L estaba bien, le hago más daño truncandola
#MatrizL_truncada = np.trunc(MatrizL * (10 ** 5)) / (10 ** 5)
MatrizU_truncada = np.trunc(MatrizU * (10 ** 5)) / (10 ** 5)

In [36]:
# b) Prueba tu programa para obtener L, U

In [37]:
# l
MatrizL

array([[  2. ,   0. ,   0. ,   0. ],
       [  3. ,   2.5,   0. ,   0. ],
       [  1. ,  -4.5, -13.6,   0. ],
       [  2. ,  -3. , -11.4,  -1. ]])

In [38]:
# U
MatrizU_truncada

array([[ 1. ,  0.5,  2. ,  0.5],
       [ 0. ,  1. , -2.8, -1. ],
       [ 0. ,  0. ,  1. ,  0. ],
       [ 0. ,  0. ,  0. ,  1. ]])

In [39]:
# c) Multiplica U, L para verificar que recuperamos A
print(np.dot(MatrizL, MatrizU_truncada))

[[ 2.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]


In [40]:
# d) Convierte tu programa en una función y pruebalo en A.

In [41]:
#Disclaimer, la mayoria de los comentarios son despues de haber acabado los ejercicios.

#Aquí explico lo último que se debe hacer para tener el programa funcionando al 100

#Bueno, ya llegamos a la última estapa de este espantoso código.
#Tenemos el LUx = v
#Haremos la sustitución Ux = y
#entonces solo debemos resolver Ly = v y despues Ux = y
#Siendo sinceros, no se porque le llamada double backward substitution, incluso en el libro se nota que la de Ly = v es foward, la 
#de Ux = y si es backward.

#Ly = v
############################################
#Foward Substitution
v = vcopy #nuevamente porque lo copiamos xd
l = MatrizL # ya es mas claro quien es quien

#la expliación de como llegué a los loop para el algoritmo de Foward y Backward Substitution están
#y deberian estar en el PDF adjunto. 
#No hay tantas versiones de esta parte del código porque nuevamente me equivoqúe yo, me hacian sentido
#cuando los hice en papel, pero al momento de probarlos no me daban lo esperado y el debugging es como las 
#demostraciones, magia momentanea.


# Forward Substitution
y = np.empty(N, float)
for i in range(N):
    y[i] = v[i] / l[i, i]
    for j in range(i):
        y[i] -= (l[i, j] * y[j]) / l[i, i]
############################################
#Ux = y
#Backsubstitution
u = MatrizU_truncada
# Backsubstitution
x = np.empty(N, float)  
for m in range(N-1, -1, -1):  
    x[m] = y[m] 
    for i in range(m+1, N): 
        x[m] -= u[m, i] * x[i] 
    x[m] /= u[m, m]  
############################################
print('x =', x)

x = [ 2. -1. -2.  1.]


In [42]:
#algo que olvide recalacar en el cacho anterior fue el v, si bien lo acarree en la fase preliminar de mi código no es necesario
#para la eliminación de Gauss, porque las matrices L, U tienen ya lo que se va a hacer a v, y si pongo el v maniuplado
#ya no da lo que debia, si bien no hace daño, se le puede quitar esa parte al código y en su lugar usar la dimensión de 
#la columna o row para la N, pero como soy un loquillo se lo vamos a pedir al usuario.

In [43]:
#Mi intento todo rancio de pasarlo a función, nunca he sido bueno con la identación.


#def DescomposicionLU(A,N):
 #   import numpy as np
#Debemos mantener una referencia a la matriz A original pues al final del programa no es la misma.
  #  O = A.copy() 
####################################################### 
#Creación del hogar de las matrices L_{i} y L_{i}^{-1}
   # U = []
    #L = []
    #for i in range(N):
     #   L.append(np.zeros((N,N),float))
      #  U.append(np.zeros((N,N),float))
######################################################        
#Pivoting
   # for m in range(N):
    #    div = A[m,m]
     #   if div == 0:
      #      for w in range(m+1,N):
       #         if A[w,m] != 0:            
        #            tempA = A[m,:].copy()
         #           A[m,:] = A[w,:]
          #          A[w,:] = tempA
           #         break
            #    else:
             #       continue
##################################################
#Gauss Elimination
    #for m in range(N):   
    ######################################
    #Creación de las matrices L_{i}, U_{i}
     #    W = L[m] 
      #   Q = U[m]
       #  z = 1/A[m,m].copy()
    #diagonal
    #for p in range(N):
     #   if p == m:
      #      W[p,p] = z
       #     Q[p,p]  = A[m,m].copy()
        #else:
         #   W[p,p] = A[m,m].copy()*z
          #  Q[p,p] = 1
    #renglón
    #for p in range(m+1,N):
     #   W[p,m] = -A[p,m].copy()*z
      #  Q[p,m] = A[p,m].copy()
    ######################################
    #div = A[m,m]
    #A[m,:] /= div 
    #for i in range(m+1,N):
     #   mult = A[i,m]
      #  A[i,:] -= mult*A[m,:]  
######################################################
# Aquí ahora debemos armar la matriz L, y U.
   # Normales = L 
    #NormalesMult = Normales[-1]
    #for i in range(len(Normales)-2, -1, -1):
     #   NormalesMult = np.dot(NormalesMult, Normales[i])
    #Inversas  = U 
    #InversasMult = Inversas[0]
    #for i in range(1, len(U)):
     #   InversasMult = np.dot(InversasMult, Inversas[i])
######################################################
    #MatrizL = InversasMult
    #MatrizU = np.dot(NormalesMult,O) 
    #Truncamiento si es necesario, solo lo hare por completez, no es necesario.
    #MatrizU_Trun = np.trunc(MatrizU * (10 ** 5)) / (10 ** 5)
    #MatrizL_Trun = np.trunc(MatrizL * (10 ** 5)) / (10 ** 5)
######################################################
    #return MatrizL_Trun, MatrizU_Trun

In [44]:
# Mi primera chamba
def DescomposicionLU(A, N):
    # Copia de A
    O = A.copy()

    # Creación del conjunto de matrices  L_{i} y L_{i}^{-1}
    U = []
    L = []
    for i in range(N):
        L.append(np.zeros((N, N), float))
        U.append(np.zeros((N, N), float))

    # Pivoting
    for m in range(N):
        div = A[m, m]
        if div == 0:
            for w in range(m+1, N):
                if A[w, m] != 0:
                    tempA = A[m, :].copy()
                    A[m, :] = A[w, :]
                    A[w, :] = tempA
                    break

    # Gauss Elimination
    for m in range(N):
        W = L[m]
        Q = U[m]
        z = 1 / A[m, m].copy()
        
        # Diagonal
        for p in range(N):
            if p == m:
                W[p, p] = z
                Q[p, p] = A[m, m].copy()
            else:
                W[p, p] = A[m, m].copy() * z
                Q[p, p] = 1
        
        # Renglón
        for p in range(m + 1, N):
            W[p, m] = -A[p, m].copy() * z
            Q[p, m] = A[p, m].copy()
        
        div = A[m, m]
        A[m, :] /= div
        
        for i in range(m + 1, N):
            mult = A[i, m]
            A[i, :] -= mult * A[m, :]

    # Matrices L y U
    Normales = L
    NormalesMult = Normales[-1]
    
    for i in range(len(Normales) - 2, -1, -1):
        NormalesMult = np.dot(NormalesMult, Normales[i])
    
    Inversas = U
    InversasMult = Inversas[0]
    
    for i in range(1, len(U)):
        InversasMult = np.dot(InversasMult, Inversas[i])

    # l, U las buenas casi, o si.
    MatrizL = InversasMult
    MatrizU = np.dot(NormalesMult, O)

    # Truncamiento si es necesario
    MatrizU_Trun = np.trunc(MatrizU * (10 ** 5)) / (10 ** 5)
    MatrizL_Trun = np.trunc(MatrizL * (10 ** 5)) / (10 ** 5)

    return MatrizL,MatrizU,MatrizL_Trun, MatrizU_Trun

In [45]:
A = array([[2,1,4,1],
           [3,4,-1,-1],
           [1,-4,1,5],
           [2,-2,1,3]],float)
MatL, MatU,MatLTrun,MatUTru  = DescomposicionLU(A, 4)
print(MatL)
print(MatU)
print(MatLTrun)
print(MatUTru)

[[  2.    0.    0.    0. ]
 [  3.    2.5   0.    0. ]
 [  1.   -4.5 -13.6   0. ]
 [  2.   -3.  -11.4  -1. ]]
[[ 1.00000000e+00  5.00000000e-01  2.00000000e+00  5.00000000e-01]
 [ 0.00000000e+00  1.00000000e+00 -2.80000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  2.77555756e-17]
 [ 0.00000000e+00  0.00000000e+00  1.55431223e-15  1.00000000e+00]]
[[  2.        0.        0.        0.     ]
 [  3.        2.5       0.        0.     ]
 [  1.       -4.5     -13.6       0.     ]
 [  2.       -3.      -11.39999  -1.     ]]
[[ 1.   0.5  2.   0.5]
 [ 0.   1.  -2.8 -1. ]
 [ 0.   0.   1.   0. ]
 [ 0.   0.   0.   1. ]]


In [46]:
def SustitucionLU(MatrizL, MatrizU, v):
    N = len(v)
    # Forward Substitution
    l = MatrizL
    y = np.empty(N, float)
    for i in range(N):
        y[i] = v[i] / l[i, i]
        for j in range(i):
            y[i] -= (l[i, j] * y[j]) / l[i, i]
    # Backsubstitution
    u = MatrizU
    x = np.empty(N, float)
    for m in range(N - 1, -1, -1):
        x[m] = y[m]
        for i in range(m + 1, N):
            x[m] -= u[m, i] * x[i]
        x[m] /= u[m, m]
    return x

In [47]:
Sus = SustitucionLU(MatL, MatU, v)
Sus2 = SustitucionLU(MatLTrun, MatUTru, v)
print('Solución sin truncamiento:',Sus)
print('Solución con truncamiento:',Sus2)

Solución sin truncamiento: [ 2. -1. -2.  1.]
Solución con truncamiento: [ 2.00002 -1.00002 -2.       0.99998]


In [48]:
# e) Usa solve para resolver el sistema de ecuaciones Ax = v y compara con tu resultado.
A = np.array([[2,1,4,1],
           [3,4,-1,-1],
           [1,-4,1,5],
           [2,-2,1,3]],float)

v = np.array([-4, 3, 9, 7], float)
x = np.linalg.solve(A, v)

print("x:", x)



x: [ 2. -1. -2.  1.]


In [49]:
#Aquí vemos que sin truncamiento se parece la solución, pero inclui las truncadas porque el efecto que buscabamos en 
#el inciso anterior era que se parecieran las matrices a las que teniamos pues, lo bueno es que el usuario puede discernir 
#cuales le convienen más.

#Ah, y si son iguales las soluciones.

In [50]:
#Probando con otra matriz
B = np.array([[1,2,4,3],
           [4,5,9,6],
           [7,8,9,9],
           [3,6,5,4]],float)
p = np.array([1,3,4,3],float)
x = np.linalg.solve(B, p)
print("x:", x) 

x: [ 0.18666667  0.42666667  0.2        -0.28      ]


In [51]:
N = len(p)
MatL, MatU,MatLTrun,MatUTru  = DescomposicionLU(B, N)

Sus = SustitucionLU(MatL, MatU, p)
Sus2 = SustitucionLU(MatLTrun, MatUTru, p)
print('Solución sin truncamiento:',Sus)
print('Solución con truncamiento:',Sus2)

Solución sin truncamiento: [ 0.18666667  0.42666667  0.2        -0.28      ]
Solución con truncamiento: [ 0.18666533  0.42666733  0.2        -0.28      ]


In [52]:
#Como ya he comentado antes, tengo problemas con ciertas cositas del python, casi me da un infarto cuando vi que no daban los mismo.
#Ahora, si bien funciona, hay excepciones y es cuando el determinante es cerca de cero o cero.
#Le metí una matriz de 3x3 con determinante cero y me dio un error, y ashí se nota que tipo de matrices no puede resolver.
